### ISSUE TITLE
Reorganization

### ISSUE THREAD

**Issue by jchristgit** [strinking/PySO#1]
I feel like a bunch of reorganization would be useful to ease work with the module.

This includes:
- [x] Moving all files to a folder called `pyso` and adding a `__init__.py` to it, so the package can be imported (lowercased because of [PEP8](https://www.python.org/dev/peps/pep-0008/#package-and-module-names))
- [x] Move all functions / classes / variables determined for the user into the "top" `pyso.` namespace by importing them in `__init__.py`
- [x] Potentially split up <https://github.com/strinking/PySO/blob/master/StackSearchModule.py> to multiple files
- [x] Rename `StackSearchModule.py` to fit to the convention of `snake_case` filenames and to better describe what it is doing. Since the search will be performed through the package instead of `StackSearchModule`, one could split up the file into the class definitions and the functions.

I can work on this tomorrow.

**Comment by lthoma5** [comment]
https://github.com/strinking/PySO/commit/4556284c9f8e00e534497bd3bcf32f9a1da36c46 -> Moved StackSearchModule.py -> pyso/stack_search_module.py and added __init__.py. Should solve the first point in your issue

Addressed point #2 with https://github.com/strinking/PySO/commit/4575e98a33adf38250a4099b6d346a88acbda3b9. Only imported the search() function as that's the only public function/class (I'm returning a dict now per everyone's suggestion)

**Comment by lthoma5** [comment]
Last two points done in reorganization. Fixed in https://github.com/strinking/PySO/commit/c0c9467406006fd9e32e236f34962a4ee0e3df4
